### ISSUE TITLE
GH historical-time organization members

### ISSUE THREAD

**Issue by zoometh** [historical-time/caa-chrono-sig#1]
@rybesh and @atomrab could you invite:
- @MartinHinz (Martin Hinz) and 
- @joeroe (Joe Roe) 
to join the organization?

**Comment by rybesh** [comment]
Done!

**Comment by zoometh** [comment]
@rybesh sorry for this late request, can you also invite: @nmazzucco ?

**Comment by rybesh** [comment]
:+1:
